FROM node:20-alpine AS builder
WORKDIR /app
ARG VITE_API_BASE_URL="https://book-publisher-backend-451315399249.asia-south1.run.app/api/v1"
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]
